Fix: Download official OpenCV Android SDK from correct path

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,14 +21,15 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
 
-    - name: Download OpenCV Android SDK
+    - name: Download and Install OpenCV Android SDK
       run: |
-        wget https://github.com/opencv/opencv/releases/download/4.10.0/opencv-4.10.0-android-sdk.zip
-        unzip opencv-4.10.0-android-sdk.zip -d opencv-sdk
+        wget -q https://github.com/opencv/opencv/releases/download/4.10.0/opencv-4.10.0-android-sdk.zip
+        unzip -q opencv-4.10.0-android-sdk.zip -d opencv-sdk
         mkdir -p chess_detector/app/libs
         find opencv-sdk -name "*.aar" -type f
-        cp opencv-sdk/OpenCV-android-sdk/sdk/*.aar chess_detector/app/libs/opencv-4.10.0.aar
-        rm opencv-4.10.0-android-sdk.zip
+        cp opencv-sdk/OpenCV-android-sdk/sdk/*.aar chess_detector/app/libs/opencv-4.10.0.aar || echo "Failed to find .aar file"
+        ls -lh chess_detector/app/libs/
+        rm -f opencv-4.10.0-android-sdk.zip
 
     - name: Grant execute permission for gradlew
       run: chmod +x chess_detector/gradlew
